spring.application.name=SecondProductService

#server.port=8082


logging.level.root=INFO
logging.level.org.springframework=ERROR
logging.level.com.scaler=DEBUG

logging.level.org.springframework.web=TRACE






#spring.datasource.url=jdbc:mysql://localhost:3306/productservicedb
#spring.datasource.username=root
#spring.datasource.password=MeriMaa@2025
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true




#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true